---
- hosts: all
  become: true
  tasks:
    - name: ensure apt cache is the latest
      apt: update_cache=yes upgrade=yes cache_valid_time=86400

- hosts: dbservers
  become: true
  vars:
    mysql_databases:
      - name: drupal
    mysql_users:
      - name: drupal
        host: "%"
        password: drupal
        priv: drupal.*:ALL
  roles:
    - geerlingguy.mysql

- hosts: cacheservers
  become: true
  roles:
    - geerlingguy.memcached

- hosts: webservers
  become: true
  vars:
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "localhost"
        root: "/var/www"
        index: "index.php index.html index.htm"
        extra_parameters: |
          # if the request starts with our frontcontroller, pass it on to fastcgi
          location ~ ^/.*\.php
          {
              fastcgi_split_path_info ^(.+.php)(/.+)$;
              fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
              fastcgi_param  QUERY_STRING       $query_string;
              fastcgi_param  REQUEST_METHOD     $request_method;
              fastcgi_param  CONTENT_TYPE       $content_type;
              fastcgi_param  CONTENT_LENGTH     $content_length;
              fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
              fastcgi_param  REQUEST_URI        $request_uri;
              fastcgi_param  DOCUMENT_URI       $document_uri;
              fastcgi_param  DOCUMENT_ROOT      $document_root;
              fastcgi_param  SERVER_PROTOCOL    $server_protocol;
              fastcgi_param  HTTPS              $https if_not_empty;
              fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
              fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;
              fastcgi_param  REMOTE_ADDR        $remote_addr;
              fastcgi_param  REMOTE_PORT        $remote_port;
              fastcgi_param  SERVER_ADDR        $server_addr;
              fastcgi_param  SERVER_PORT        $server_port;
              fastcgi_param  SERVER_NAME        $server_name;
              fastcgi_param PATH_INFO         $fastcgi_path_info;
              fastcgi_param PATH_TRANSLATED   $document_root$fastcgi_path_info;
              fastcgi_read_timeout 300;
              fastcgi_pass unix:/var/run/php5-fpm.sock;
              fastcgi_index index.php;
          }
          fastcgi_param  REDIRECT_STATUS    200;

    nginx_remove_default_vhost: true
    php_packages:
      - php-apc
      - php-pear
      - php5
      - php5-cli
      - php5-curl
      - php5-fpm
      - php5-gd
      - php5-mcrypt
      - php5-mysql
      - php5-pgsql
      - php5-sqlite
    php_webserver_daemon: "nginx"
    php_enable_php_fpm: true
    php_fpm_listen: "/var/run/php5-fpm.sock"
  roles:
    - geerlingguy.nginx
    - geerlingguy.php
- hosts: codeservers
  become: true
  roles:
    - drupal
