; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[coder][version] = "2.2"

projects[ctools][version] = "1.4"

projects[date][version] = "2.7"

projects[devel][version] = "1.4"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[panels][version] = "3.4"

projects[link][version] = "1.2"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.5"

; Themes
projects[zen][version] = "5.4"

