# Set variables for Digital Ocean cluster
---
- hosts: all
  tasks:
    - name: Set global variables
      set_fact:
        drupal_init: true
        drupal_site_machinename: mydrupalsite
        drupal_root_dir: /srv/mydrupalsite
        drupal_docroot_dir: /srv/mydrupalsite/docroot
        drupal_mysql_host: cecil
        drupal_mysql_database: mydrupalsite
        drupal_mysql_user: mydrupalsite
        drupal_mysql_password: '{{ secret_mysql_password }}'
        drupal_mysql_port: ''
        drupal_git_repository: /srv/git/mydrupalsite.git
        mysql_databases:
          - name: mydrupalsite
        mysql_users:
          - name: mydrupalsite
            host: '%'
            password: '{{ secret_mysql_password }}'
            priv: mydrupalsite.*:ALL
        glusterfs_volume_host: cecil
        glusterfs_volume_name: mydrupalsite
        memcached_host: cecil
        glusterfs_force: yes
