# Set variables for Vagrant cluster
---
- hosts: all
  tasks:
    - name: Set global variables
      set_fact:
        mysql_databases:
          - name: drupal
        mysql_users:
          - name: drupal
            host: '%'
            password: drupal
            priv: drupal.*:ALL
        glusterfs_volume_host: db
        glusterfs_volume_name: drupal_files
        glusterfs_force: yes
        memcached_host: db
        drupal_init: yes
        drupal_core_version: 7.x
        drupal_root_dir: /vagrant
        drupal_docroot_dir: /vagrant/docroot
        drupal_mysql_host: db
        drupal_mysql_database: drupal
        drupal_mysql_user: drupal
        drupal_mysql_password: drupal
        drupal_mysql_port: ''
        drupal_extra_settings: |
          $conf['cache_backends'][] = 'sites/all/modules/contrib/memcache/memcache.inc';
          $conf['cache_default_class'] = 'MemCacheDrupal';
          $conf['cache_class_cache_form'] = 'DrupalDatabaseCache';
          $conf['memcache_servers'] = array(
            'db:11211' => 'default',
          );
